version: "3.8"

services:
  go:
    container_name: task-copilot-server
    build:
      context: ./golang
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./mysql/.env.local
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./golang
        target: /go/src

  db:
    container_name: task-copilot-db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    tty: true
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file:
      - ./mysql/.env.local
    volumes:
      - type: volume
        source: mysql_data_volume
        target: /var/lib/mysql

volumes:
  mysql_data_volume:
    name: mysql_data_volume
