up:
	docker compose up -d

down:
	docker compose down

ps:
	docker compose ps

go:
	docker compose exec go sh

db:
	docker compose exec db bash

build:
	docker build -t us-west1-docker.pkg.dev/task-copilot-403811/task-api/api-image:latest .

push:
	docker push us-west1-docker.pkg.dev/task-copilot-403811/task-api/api-image:latest